name: check-does-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 强制所有 Actions 运行在 Node.js 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: voxy-artifacts
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 30
          compression-level: 6
          overwrite: true
          include-hidden-files: false
          archive: true
